version: '3.7'

services:
  nest-app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - .:/usr/src/nest-app
      - /usr/src/nest-app/node_modules
      - /usr/src/nest-app/dist
    ports:
      - 3030:3030
